# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='documents/%Y/%m/%d/')),
            ],
        ),
    ]
