# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20180225_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='date',
            field=models.DateField(),
        ),
    ]
