# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20180225_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('num', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('split', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('debit_account', models.CharField(max_length=200)),
                ('credit_account', models.CharField(max_length=200)),
            ],
        ),
    ]
