# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='num',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
