# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180228_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='books',
            name='memo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='split',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
