# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20180228_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='classification',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='books',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='books',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
    ]
