# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20180228_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='books',
            unique_together=set([('Type', 'memo', 'date', 'amount')]),
        ),
    ]
