# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_auto_20180228_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='books',
            unique_together=set([('date', 'memo', 'num', 'amount', 'classification')]),
        ),
    ]
