# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20180228_1830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='books',
            unique_together=set([('memo', 'classification')]),
        ),
    ]
