# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
